# Generated by Django 4.2.20 on 2025-03-17 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
